# main_folder/docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env  

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: Bank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
