# Generated by Django 4.2.4 on 2023-11-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='interest_type',
            field=models.CharField(choices=[('fixed', 'Fixed'), ('reducing', 'Reducing')], default='fixed', max_length=100),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=100),
        ),
    ]
