# Generated by Django 4.2.4 on 2023-11-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_interest_type_loan_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Fixed'), ('reducing', 'Reducing')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('business', 'Business')], max_length=100, null=True),
        ),
    ]
