# Generated by Django 4.2.4 on 2023-11-12 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_bankpersonnel_is_active_and_more'),
        ('funds', '0002_generalinfo_fundrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funds.fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.loanprovider')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
