# Generated by Django 4.2.4 on 2023-11-12 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0004_fundrequest_verified_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fundrequest',
            old_name='verified_by',
            new_name='assigned_by',
        ),
        migrations.AddField(
            model_name='fundrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
