# Generated by Django 4.2.4 on 2023-11-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0005_rename_verified_by_fundrequest_assigned_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
