# Generated by Django 4.2.4 on 2023-11-12 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0006_fundrequest_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fundrequest',
            name='reason',
        ),
    ]
