# Generated by Django 4.2.7 on 2023-11-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funds', '0007_remove_fundrequest_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundrequest',
            name='is_payed',
            field=models.BooleanField(default=False),
        ),
    ]
