# Generated by Django 4.2.4 on 2023-11-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loancustomer',
            name='max_income',
            field=models.FloatField(default=0),
        ),
    ]
