# Generated by Django 4.2.4 on 2023-11-10 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_loancustomer_max_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancustomer',
            name='max_duration',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='max_interest',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='max_value',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='min_duration',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='min_interest',
        ),
        migrations.RemoveField(
            model_name='loancustomer',
            name='min_value',
        ),
    ]
