# Generated by Django 4.2.4 on 2023-11-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_loancustomer_max_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanprovider',
            name='company_branch',
        ),
        migrations.RemoveField(
            model_name='loanprovider',
            name='company_name',
        ),
        migrations.AddField(
            model_name='loanprovider',
            name='max_amount',
            field=models.FloatField(default=0),
        ),
    ]
