# Generated by Django 4.2.4 on 2023-11-10 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_loanprovider_company_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankpersonnel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loancustomer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='loanprovider',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
